version: "3.1"

services:
  web:
    build:
      context: web
    command: bash -c "yarn install && yarn start"
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
      - node_modules:/app/node_modules
    environment:
      CI: "true"
      REACT_APP_API_URL: http://localhost:5000/graphql
      REACT_APP_SUBSCRIPTION_URL: ws://localhost:5000/graphql

  api:
    build:
      context: api
    command: ./entrypoint.sh
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./api:/app
      - bin:/app/MyApi/bin
      - obj:/app/MyApi/obj
      - bin_data:/app/MyApi.Data/bin
      - obj_data:/app/MyApi.Data/obj
    links:
      - db:db
    environment:
      DB_HOST: db
      DB_DATABASE: mydb
      DB_USERNAME: admin
      DB_PASSWORD: password

  db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db:db

volumes:
  bin:
  obj:
  bin_data:
  obj_data:
  node_modules:
