// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MyApi.Data.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20200526184654_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MyApi.Data.Entities.AuthorEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("authors");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Robert C. Martin"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Claus Matzinger"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Matt Neuburg"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Sandi Metz"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Mark J. Price"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Gene Kim"
                        });
                });

            modelBuilder.Entity("MyApi.Data.Entities.BookEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("AuthorId")
                        .HasColumnName("author_id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AuthorId = 1L,
                            Name = "Clean Code: A Handbook of Agile Software Craftsmanship"
                        },
                        new
                        {
                            Id = 2L,
                            AuthorId = 1L,
                            Name = "Clean Architecture: A Craftsman's Guide to Software Structure and Design"
                        },
                        new
                        {
                            Id = 3L,
                            AuthorId = 1L,
                            Name = "Clean Agile: Back to Basics"
                        },
                        new
                        {
                            Id = 4L,
                            AuthorId = 2L,
                            Name = "Rust Programming Cookbook"
                        },
                        new
                        {
                            Id = 5L,
                            AuthorId = 3L,
                            Name = "iOS 13 Programming Fundamentals with Swift: Swift, Xcode, and Cocoa Basics"
                        },
                        new
                        {
                            Id = 6L,
                            AuthorId = 4L,
                            Name = "Practical Object-Oriented Design: An Agile Primer Using Ruby"
                        },
                        new
                        {
                            Id = 7L,
                            AuthorId = 5L,
                            Name = "C# 8.0 and .NET Core 3.0 – Modern Cross-Platform Development: Build applications with C#, .NET Core, Entity Framework Core, ASP.NET Core, and ML.NET using Visual Studio Code, 4th Edition"
                        },
                        new
                        {
                            Id = 8L,
                            AuthorId = 6L,
                            Name = "The Phoenix Project: A Novel about IT, DevOps, and Helping Your Business Win"
                        },
                        new
                        {
                            Id = 9L,
                            AuthorId = 6L,
                            Name = "The Unicorn Project: A Novel about Developers, Digital Disruption, and Thriving in the Age of Data"
                        },
                        new
                        {
                            Id = 10L,
                            AuthorId = 6L,
                            Name = "The DevOps Handbook: How to Create World-Class Agility, Reliability, and Security in Technology Organizations"
                        });
                });

            modelBuilder.Entity("MyApi.Data.Entities.BookEntity", b =>
                {
                    b.HasOne("MyApi.Data.Entities.AuthorEntity", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
